yutool:
  token: 111
  wx:
    redisTokenKey: yutools_wx_access_token1
    #公众号appid
#    appid: wx8c39f3c5922f3fbb
    appid: wxda6555b2670a8bde
    #公众号appsecret
#    appsecret: e383c7403b2a85cb52d407858444a9c9
    appsecret: d8db9c5164ac6579bb9c86b50da42f7e
    #小程序appid 可选 需要跳转到小程序时添加
    appletAppid: xxx
    #小程序appsecret 可选
    appletAppsecret: xxx
    #网页授权回调地址
    redirectUri: axc

spring:
  redis:
    host: 127.0.0.1
    password: root
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8